.Additional testing instructions
- Report issues in https://app.asana.com/0/1116666533974620/list[Asana, window=\"_blank\"]
- If reporting a mobile issue, also include https://whatsmybrowser.org/[browser information].
- Test the website and onboarding in multiple browsers, IE, Firefox, & Chrome. 
- Test core functionality on mobile IPhone/Safari & Android default browser.
- Test forward / backward navigation on all platforms.
- Reference: Chrome screenshot https://chrome.google.com/webstore/detail/scrnli-screenshot-tool-an/ialiedlpfknneamnbemcgmaboleiccdd[plugin].
